apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
    name: ourflows-com-tls
spec:
    secretName: ourflows-com
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: ourflows.com
    dnsNames:
        - ourflows.com
        - www.ourflows.com
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - ourflows.com
                - www.ourflows.com
